export const hospitalKnowledge = {
  hospital: {
    name: 'Sanjeevani Hospital',
    tagline: 'Caring for you always.',
    address: '25, Street Number 5, Near Mangalwari Bazar, Jaripatka, Nagpur – 440014',
    phone: '0712-648864',
    whatsapp: '919822234434',
    email: 'care@sanjeevanihospital.in',
    established: 'Since 2001',
    hours: 'Specific outpatient hours are not listed in the available hospital information. Please contact the hospital to confirm.',
  },
  departments: [
    { id: 'general-medicine', name: 'General Medicine', focus: 'Primary consultation and chronic care', description: 'Primary consultations and long-term health management.' },
    { id: 'cardiology', name: 'Cardiology', focus: 'Heart and diabetes management', description: 'Cardiac screening, prevention, and follow-up care.' },
    { id: 'orthopedics', name: 'Orthopedics', focus: 'Bone, joint, and mobility care', description: 'Support for fractures, joints, mobility, and musculoskeletal concerns.' },
    { id: 'gynecology', name: 'Gynecology & Obstetrics', focus: 'Women’s health and maternity care', description: 'Women’s health, pregnancy support, and preventive care.' },
    { id: 'pediatrics', name: 'Pediatrics', focus: 'Child and adolescent wellness', description: 'Consultations and follow-up for children and adolescents.' },
    { id: 'emergency', name: 'Emergency & Accident Care', focus: 'Immediate intervention and trauma support', description: 'Emergency and accident care. For immediate danger, contact local emergency services.' },
  ],
  doctors: [
    { id: 'dr-sanjeevani-ramteke', name: 'Dr. Sanjeevani Ramteke', qualification: 'MBBS, M.D. Strirog Tadnya', specialty: 'Consulting Physician & Surgeon', department: 'General Medicine' },
    { id: 'dr-kishore-ramteke', name: 'Dr. Kishore Ramteke', qualification: 'MBBS (Bom), MD, FCCM, CCDM', specialty: 'Consulting Physician', department: 'General Medicine' },
    { id: 'dr-pranay-lanjewar', name: 'Dr. Pranay Lanjewar', qualification: 'MBBS, MD', specialty: 'Consulting Physician, Cardiologist & Diabetologist', department: 'Cardiology' },
    { id: 'dr-madhukar-thakre', name: 'Dr. Madhukar Thakre', qualification: 'MBBS, MS', specialty: 'General Surgeon & Cancer Specialist', department: 'Emergency' },
    { id: 'dr-pitamber-masram', name: 'Dr. Pitamber Masram', qualification: 'MBBS, MS', specialty: 'General Surgeon', department: 'Emergency' },
    { id: 'dr-pawan-gulhane', name: 'Dr. Pawan Gulhane', qualification: 'MBBS, DGO', specialty: 'Gynecologist & Obstetrician', department: 'Gynecology' },
    { id: 'dr-divya-assudani', name: 'Dr. Divya Assudani', qualification: 'MBBS, MS', specialty: 'Gynecologist & Obstetrician', department: 'Gynecology' },
    { id: 'dr-nayankumar', name: 'Dr. Nayankumar', qualification: 'MBBS, DCH', specialty: 'Pediatrician', department: 'Pediatrics' },
    { id: 'dr-ashish-assudani', name: 'Dr. Ashish Assudani', qualification: 'MBBS, DCH', specialty: 'Orthopedic Surgeon', department: 'Orthopedics' },
    { id: 'dr-sanjeevani-lanjewar', name: 'Dr. Sanjeevani Lanjewar', qualification: 'MBBS, DA', specialty: 'Anaesthesiologist & Intensivist', department: 'Emergency' },
  ],
  services: [
    { id: 'emergency', title: 'Emergency & Accident Care', description: 'Immediate clinical attention and trauma support for urgent medical situations.' },
    { id: 'general-medicine', title: 'General Medicine', description: 'Consultation and treatment for a wide range of health concerns.' },
    { id: 'cardiology', title: 'Cardiology & Diabetes Care', description: 'Check-ups, preventive support, and specialist follow-up.' },
    { id: 'gynecology', title: 'Gynecology & Maternity', description: 'Women’s health, prenatal consultations, and maternity support.' },
    { id: 'orthopedics', title: 'Orthopedic Care', description: 'Specialist consultations for joint, fracture, and mobility concerns.' },
    { id: 'pediatrics', title: 'Pediatrics', description: 'Dedicated consultations for infants, children, and adolescents.' },
  ],
  faqs: [
    { question: 'Do I need to book an appointment in advance?', answer: 'Appointments are recommended for consultations, especially in specialist departments. Walk-in cases are supported for emergencies.' },
    { question: 'What is the hospital address?', answer: 'Sanjeevani Hospital is located at 25, Street Number 5, Near Mangalwari Bazar, Jaripatka, Nagpur – 440014.' },
    { question: 'Is emergency care available?', answer: 'The hospital offers emergency and accident care. For immediate danger, contact local emergency services.' },
    { question: 'Can I contact the hospital by WhatsApp?', answer: 'Yes, use the WhatsApp quick-access button or the phone number listed on the contact page.' },
  ],
  appointmentGuide: 'The appointment request form asks for full name, phone number, preferred date, department, and an optional email and message. Submitting the form creates a request; the hospital team must confirm the appointment.',
  insurance: 'Insurance, cashless coverage, and accepted plans are not specified in the verified hospital information. Contact the hospital directly to confirm.',
};